version: "3"

services:
  app:
    container_name: web_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - tickets-data:/var/lib/postgresql/data

volumes:
  tickets-data:
