version: "3"

services:
  app:
    container_name: web_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: "python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: tickets
      POSTGRES_DB: tickets
      POSTGRES_PASSWORD: tickets
    volumes:
      - tickets-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  tickets-data:
